# Generated by Django 3.2.20 on 2023-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0002_bookingsession_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
