# Generated by Django 3.2.20 on 2023-08-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0003_bookingsession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='date',
            field=models.DateField(auto_now=True, help_text='Select date'),
        ),
    ]
