# Generated by Django 3.2.20 on 2023-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0005_auto_20230822_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
